### ISSUE TITLE
Closing overlay when link selected

### ISSUE THREAD

**Issue by iammichaelgarcia** [stardothosting/shift8-fullnav#1]
I don't know if this would be considered an issue really, but I was not sure where it would be best to add this.  However, I am using the plugin on a single page site and by default when you click a nav item the window does not close.  So the user has to select the "X" to close the window. 

I added a call to the function that closes the window when you select the "X" and that is working just fine.  Thought I would share it as a possible option to add in future developments.

**Comment by stardothosting** [comment]
Thanks for the input! Please do indeed share and once tested I will submit an update.

**Comment by iammichaelgarcia** [comment]
There is probably a much easier/efficient way to do this but this is what I did to make it work and not conflict with the rest of the code.

in the main.js file I added this function...

```javascript
// Function to close nav items on click
    $('.fn-primary-nav-trigger-item').on('click', function(){
        $('.fn-menu-icon').toggleClass('is-clicked');
        $('.fn-header').toggleClass('menu-is-open');
        //in firefox transitions break when parent overflow is changed, so we need to wait for the end of the trasition to give the body an overflow hidden
        if( $('.fn-primary-nav').hasClass('is-visible') ) {
            $('.fn-primary-nav').removeClass('is-visible').one('webkitTransitionEnd otransitionend oTransitionEnd msTransitionEnd transitionend',function(){
            $('body').removeClass('overflow-hidden');
            });
        } else {
            $('.fn-primary-nav').addClass('is-visible').one('webkitTransitionEnd otransitionend oTransitionEnd msTransitionEnd transitionend',function(){
            $('body').addClass('overflow-hidden');
            });
        }
    });
```

in the functions.php file I modified funciton start_el attributes output for the link to include a call to the function above.

```php
    function start_el(&$output, $item, $depth = 0, $args = array(), $id = 0) {
        global $wp_query;
		$this->curItem = $item;
		$class_names = 'fn-menu-mobile-parent fn-menu-mobile-parent-item-' . $item->ID;

		$output .= '<li class="' . $class_names . '">';
        $attributes  = !empty($item->attr_title) ? ' title="' . esc_attr($item->attr_title) . '"' : '';
        $attributes .= !empty($item->target) ? ' target="' . esc_attr($item->target) . '"' : '';
        $attributes .= !empty($item->xfn) ? ' rel="' . esc_attr($item->xfn) . '"' : '';
        $attributes .= !empty($item->url) ? ' href="' . esc_attr($item->url) . '"' : '';


        $item_output = $args->before;
// Modify output of link to include class reference for nav-trigger-item
// NOTE: does not need the 'is-clicked' class on this plugin update verison.  Prior versions needed the 'is-clicked' class as well
        $item_output .= '<a' . $attributes . ' class="fn-primary-nav-trigger-item">';
        $item_output .= $args->link_before . apply_filters('the_title', $item->title, $item->ID);
        $item_output .= '</a>';
        $item_output .= $args->after;

        $output .= apply_filters('walker_nav_menu_start_el', $item_output, $item, $depth, $args);

		if (!$depth) {
			$output .= '<script>
                    		jQuery(".fn-menu-mobile-parent-item-' . $item->ID . '").click( function() {
							if (jQuery(".fn-menu-mobile-parent-item-' . $item->ID . ' #fn-arrow-dropdown").hasClass("fn-arrow-down")) {
								jQuery(".fn-menu-mobile-parent-item-' . $item->ID . ' #fn-arrow-dropdown").removeClass("fn-arrow-down");
								jQuery(".fn-menu-mobile-parent-item-' . $item->ID . ' #fn-arrow-dropdown").addClass("fn-arrow-up");
							} else {
								jQuery(".fn-menu-mobile-parent-item-' . $item->ID . ' #fn-arrow-dropdown").removeClass("fn-arrow-up");
								jQuery(".fn-menu-mobile-parent-item-' . $item->ID . ' #fn-arrow-dropdown").addClass("fn-arrow-down");
							}
							jQuery(".fn-mobile-dropdown-content-' . $item->ID . '").slideToggle();
					});
					</script>';
		}
```

**Comment by iammichaelgarcia** [comment]
I just noticed that since a recent update this is not working.  I have not dug into the code much to see what changed from before.  @stardothosting, do you have some ideas?  I'd like to get this function going again if possible.

**Comment by stardothosting** [comment]
Hello!

I could add to the js/main.js file additional triggers to add/remove the is-clicked logic when .fn-primary-nav li a is clicked. That would trigger the clicked / not-clicked action that normally happens for the fn-main-nav-trigger.

I'll push out a release with this additional logic in the next day or two.

Thanks

**Comment by stardothosting** [comment]
Please try adding this code to js/main.js (within the document ready) 

`    //open/close primary navigation if menu option is clicked
    $('.mobile-menu li a').on('click', function(){
        $('.fn-menu-icon').toggleClass('is-clicked');
        $('.fn-header').toggleClass('menu-is-open');
        //in firefox transitions break when parent overflow is changed, so we need to wait for the end of the trasition to give the body an overflow hidden
        if( $('.fn-primary-nav').hasClass('is-visible') ) {
            $('.fn-primary-nav').removeClass('is-visible').one('webkitTransitionEnd otransitionend oTransitionEnd msTransitionEnd transitionend',function(){
            $('body').removeClass('overflow-hidden');
            });
        } else {
            $('.fn-primary-nav').addClass('is-visible').one('webkitTransitionEnd otransitionend oTransitionEnd msTransitionEnd transitionend',function(){
            $('body').addClass('overflow-hidden');
            });
        }
    });`

let me know if this works!

**Comment by iammichaelgarcia** [comment]
That worked like a charm!  Thank you.
